env: 'pressureplate'

env_args:
  map_name: 'linear-4p'
  episode_limit: 400


buffer_size: 5000
batch_size: 32
test_nepisode: 32
test_interval: 5000
log_interval: 2000
runner_log_interval: 2000
learner_log_interval: 2000
t_max: 1000000